"""Build docs/source-traceability.{csv,md} from the live ontology.

For every minted J-FIBO term, emit a row:
    jfibo_term | en_label | ja_label | status | dcterms:source | parent_class
    EDINET_alignment_count | shape_count

This is the canonical artifact for Japanese institutional review. The
relationship between a J-FIBO concept and its statutory / regulatory /
EDINET / FIBO anchor must be visible at a glance.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, OWL, RDF, RDFS, SKOS

REPO = Path(__file__).resolve().parents[1]
JPFIBO = Namespace("https://w3id.org/jfibo/ontology/JP/core/")
OUT_CSV = REPO / "docs" / "source-traceability.csv"
OUT_MD = REPO / "docs" / "source-traceability.md"


def _load_aggregate() -> Graph:
    g = Graph()
    for p in sorted((REPO / "ontology").glob("jfibo-*.ttl")):
        g.parse(p)
    return g


def _label(g: Graph, s: URIRef, lang: str) -> str:
    for o in g.objects(s, SKOS.prefLabel):
        if isinstance(o, Literal) and o.language == lang:
            return str(o)
    for o in g.objects(s, RDFS.label):
        if isinstance(o, Literal) and o.language == lang:
            return str(o)
    return ""


def _status(g: Graph, s: URIRef) -> str:
    for o in g.objects(s, JPFIBO.status):
        return str(o)
    return ""


def _sources(g: Graph, s: URIRef) -> list[str]:
    return sorted(str(o) for o in g.objects(s, DCTERMS.source))


def _parents(g: Graph, s: URIRef) -> list[str]:
    return sorted(str(o) for o in g.objects(s, RDFS.subClassOf) if not isinstance(o, type(URIRef(""))) or "/JP/core/" not in str(o))


def _all_parents(g: Graph, s: URIRef) -> list[str]:
    return sorted(str(o) for o in g.objects(s, RDFS.subClassOf))


def main() -> int:
    g = _load_aggregate()
    minted = sorted(
        {s for s in g.subjects(RDF.type, OWL.Class) if str(s).startswith(str(JPFIBO))}
        | {s for s in g.subjects(RDF.type, OWL.ObjectProperty) if str(s).startswith(str(JPFIBO))}
        | {s for s in g.subjects(RDF.type, OWL.DatatypeProperty) if str(s).startswith(str(JPFIBO))}
        | {s for s in g.subjects(RDF.type, OWL.AnnotationProperty) if str(s).startswith(str(JPFIBO))}
        | {s for s in g.subjects(RDF.type, OWL.NamedIndividual) if str(s).startswith(str(JPFIBO))},
        key=str,
    )

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["jfibo_term", "label_en", "label_ja", "status", "kind", "parents", "sources"])
        for s in minted:
            kinds = [k.split("#")[-1] for k in g.objects(s, RDF.type) if str(k).startswith("http://www.w3.org/2002/07/owl")]
            w.writerow([
                str(s).rsplit("/", 1)[-1],
                _label(g, s, "en"),
                _label(g, s, "ja"),
                _status(g, s),
                "; ".join(sorted(set(kinds))),
                "; ".join(_all_parents(g, s)),
                "; ".join(_sources(g, s)),
            ])

    # Human-facing markdown summary
    lines = [
        "# J-FIBO source traceability (v1.1)",
        "",
        "Every minted J-FIBO term, its bilingual labels, status, parent class,",
        "and the regulatory / statutory / FIBO source it cites via `dcterms:source`.",
        "",
        "Auto-generated by `scripts/build_source_traceability.py` from the live",
        "ontology. Reproducible — do not edit by hand.",
        "",
        f"Term count: **{len(minted)}**.",
        "",
        "Machine-readable: [`source-traceability.csv`](source-traceability.csv).",
        "",
        "## Coverage by source domain",
        "",
    ]
    # Tally sources by hostname
    from collections import Counter
    from urllib.parse import urlparse
    host_counts: Counter = Counter()
    for s in minted:
        for src in _sources(g, s):
            try:
                host_counts[urlparse(src).hostname or src] += 1
            except Exception:
                host_counts[src] += 1
    lines.append("| Source host | Citing terms |")
    lines.append("|---|---:|")
    for host, n in host_counts.most_common():
        lines.append(f"| `{host}` | {n} |")
    lines.append("")
    lines.append("## All terms")
    lines.append("")
    lines.append("| Term | Label (EN) | Label (JA) | Status | Sources |")
    lines.append("|---|---|---|---|---|")
    for s in minted:
        local = str(s).rsplit("/", 1)[-1]
        srcs = _sources(g, s)
        src_str = "<br/>".join(f"[{i+1}]({u})" for i, u in enumerate(srcs)) or "—"
        lines.append(
            f"| `jfibo:{local}` | {_label(g, s, 'en') or '—'} | "
            f"{_label(g, s, 'ja') or '—'} | {_status(g, s) or '—'} | {src_str} |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV.relative_to(REPO)} ({len(minted)} terms)")
    print(f"wrote {OUT_MD.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
